"""
Write ``numbers.tex`` (one macro per number quoted in the text) and the LaTeX
tables in ``tables/`` from the measurement files in ``results/``.
"""
import sys
import json
import datetime
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
from style import REPORT, RESULTS, TABLES, REDUX, DATASETS, NO_OBJECT  # noqa: E402

ENOISE = (4.67, 5.06)
EGAIN = (1.65, 1.47)
PUBLISHED_FAST = (7.0, 7.2)


def load(name):
    with open(RESULTS / name) as fh:
        return json.load(fh)


def fmt(x, nd=2):
    return f'{x:.{nd}f}'


def pm(v, e, nd=2):
    return f'\\num{{{v:.{nd}f} \\pm {e:.{nd}f}}}'


def write_table(name, body):
    (TABLES / f'{name}.tex').write_text(body)
    print(f'wrote tables/{name}.tex')


class Numbers:
    def __init__(self):
        self.lines = ['% Generated by scripts/make_tables.py -- do not edit']

    def __setitem__(self, key, value):
        self.lines.append(f'\\newcommand{{\\{key}}}{{{value}}}')

    def write(self):
        (REPORT / 'numbers.tex').write_text('\n'.join(self.lines) + '\n')
        print('wrote numbers.tex')


def epoch_label(key):
    ep, night = key.split(' ')
    y, m = ep.split('-')
    return datetime.date(int(y), int(m), 1).strftime('%Y %b')


# --------------------------------------------------------------- detector ---
def detector_tables(N):
    det = load('detector.json')
    bias = det['bias']
    keys = sorted(bias)
    N['nBiasEpochs'] = str(len(keys))
    from style import RAW
    N['nFramesSurvey'] = str(len(list(RAW.glob('*/ccd*c1.fits'))))

    # Read noise table
    rows = []
    for k in keys:
        b = bias[k]
        rows.append(f"{epoch_label(k)} & {b['1']['n_frames']} & "
                    f"{pm(b['1']['ron_e'], b['1']['ron_e_std'])} & {fmt(b['1']['ron_oscan_e'])} & "
                    f"{pm(b['2']['ron_e'], b['2']['ron_e_std'])} & {fmt(b['2']['ron_oscan_e'])} \\\\")
    r1 = np.array([bias[k]['1']['ron_e'] for k in keys])
    r2 = np.array([bias[k]['2']['ron_e'] for k in keys])
    m1, s1 = r1.mean(), r1.std(ddof=1) / np.sqrt(r1.size)
    m2, s2 = r2.mean(), r2.std(ddof=1) / np.sqrt(r2.size)
    N['ronAmpOne'] = pm(m1, s1)
    N['ronAmpTwo'] = pm(m2, s2)
    exc = 100 * (np.array([m1 / ENOISE[0], m2 / ENOISE[1]]) - 1)
    N['ronExcessRange'] = f'{exc.min():.0f}--{exc.max():.0f}'
    write_table('readnoise', r'''\begin{table}[t]
  \centering\small
  \caption{Read noise (\si{\electron}) per epoch, from bias-pair differences
    (mean $\pm$ standard deviation over pairs) and from the overscan scatter, for
    the gains in the \code{EGAIN} keyword. The published Fast-mode values are 7.0
    and 7.2~\si{\electron}; the \code{ENOISE} keyword gives 4.67 and
    5.06~\si{\electron}.}
  \label{tab:ron}
  \begin{tabular}{lrcccc}
    \toprule
    & & \multicolumn{2}{c}{Amplifier 1} & \multicolumn{2}{c}{Amplifier 2} \\
    \cmidrule(lr){3-4}\cmidrule(lr){5-6}
    Epoch & $N_{\rm bias}$ & pairs & overscan & pairs & overscan \\
    \midrule
''' + '\n'.join('    ' + r for r in rows) + f'''
    \\midrule
    Mean & & {pm(m1, s1)} & & {pm(m2, s2)} & \\\\
    \\bottomrule
  \\end{{tabular}}
\\end{{table}}
''')

    # Gain table
    ptc = det['ptc']
    rows, g1, g2, e1, e2, rej = [], [], [], [], [], []
    for k in sorted(ptc):
        p = ptc[k]
        night, grism, aper, filt, t = k.split(' ')
        ok = all(np.isfinite(p[a]['gain']) and p[a]['n_points'] >= 10 for a in '12')
        # A set is kept if both gains are within 10% of EGAIN.  Larger departures
        # are produced by lamp or illumination changes between the two exposures
        # of a pair, which the PTC cannot separate from shot noise.
        ok &= all(abs(p[a]['gain'] / EGAIN[int(a) - 1] - 1) < 0.10 for a in '12')
        mark = '' if ok else '$^\\dagger$'
        rows.append(f"{night.replace('_', r'\_')} & {grism} & {aper.replace('_', r'\_')} & {t} & "
                    f"{p['1']['n_pairs']} & {pm(p['1']['gain'], p['1']['gain_err'], 3)} & "
                    f"{pm(p['2']['gain'], p['2']['gain_err'], 3)}{mark} \\\\")
        if ok:
            g1.append(p['1']['gain']); e1.append(p['1']['gain_err'])
            g2.append(p['2']['gain']); e2.append(p['2']['gain_err'])
        else:
            rej.append(k)
    g1, g2 = np.array(g1), np.array(g2)
    # Scatter between sets dominates the formal errors, so quote the mean and the
    # standard error of the mean.
    G1, G2 = g1.mean(), g2.mean()
    E1, E2 = g1.std(ddof=1) / np.sqrt(g1.size), g2.std(ddof=1) / np.sqrt(g2.size)
    N['gainAmpOne'] = pm(G1, E1)
    N['gainAmpTwo'] = pm(G2, E2)
    N['nPtcRejected'] = str(len(rej))
    N['gainAgreement'] = f'{100 * max(abs(G1 / EGAIN[0] - 1), abs(G2 / EGAIN[1] - 1)):.0f}'
    best = max((k for k in ptc if k not in rej),
               key=lambda k: ptc[k]['1']['n_points'] + ptc[k]['2']['n_points'])
    night, grism, aper, filt, t = best.split(' ')
    N['ptcBest'] = f"{grism} {aper.replace('_', r'\_')} flats of {night.replace('_', r'\_')} ({t})"
    (RESULTS / 'ptc_best.txt').write_text(best)
    write_table('gain', r'''\begin{table}[t]
  \centering\small
  \caption{Gain (\si{\electron\per\adu}) from photon-transfer curves of flat pairs.
    Uncertainties are bootstrap estimates for each set. Sets marked $\dagger$
    depart from \code{EGAIN} by more than 10\,\% on at least one amplifier,
    because the lamp or illumination changed between the exposures of a pair, and
    are excluded from the mean.}
  \label{tab:gain}
  \begin{tabular}{llllrcc}
    \toprule
    Night & Grism & Slit/mask & $t_{\rm exp}$ & Pairs & Amp.~1 & Amp.~2 \\
    \midrule
''' + '\n'.join('    ' + r for r in rows) + f'''
    \\midrule
    \\multicolumn{{5}}{{l}}{{Mean of accepted sets}} & {pm(G1, E1)} & {pm(G2, E2)} \\\\
    \\multicolumn{{5}}{{l}}{{\\code{{EGAIN}}}} & 1.65 & 1.47 \\\\
    \\bottomrule
  \\end{{tabular}}
\\end{{table}}
''')

    # Bias levels and residuals
    lv = det['overscan_level']
    lev1 = np.array([lv[k]['1'][0] for k in lv])
    lev2 = np.array([lv[k]['2'][0] for k in lv])
    N['biasLevelSpread'] = f'{max(np.ptp(lev1), np.ptp(lev2)):.0f}'
    N['biasLevelNightly'] = f'{max(max(v["1"][1], v["2"][1]) for v in lv.values()):.0f}'
    prof = np.load(RESULTS / 'bias_profiles.npz')
    good = np.ones(2048, bool)
    for c1, c2 in det['bpm_ranges']:
        good[c1:c2 + 1] = False
    good[:20] = good[-20:] = False
    resid = max(np.max(np.abs(prof[k][good] - np.median(prof[k][good]))) for k in prof.files)
    N['biasResidMax'] = f'{np.ceil(resid):.0f}'

    # Persistent bad columns outside the mask
    from collections import Counter
    c = Counter(x for v in det['bad_column_candidates'].values() for x in v)
    pers = sorted(k for k, n in c.items() if n >= 4)
    inb = lambda x: any(a <= x <= b for a, b in det['bpm_ranges'])      # noqa: E731
    extra = [x for x in pers if not inb(x)]
    lo = [x for x in extra if x < 1024]
    hi = [x for x in extra if x >= 1024]
    N['edgeExtraOne'] = f'{min(lo)}--{max(lo)}' if len(lo) > 1 else (str(lo[0]) if lo else '--')
    N['edgeExtraTwo'] = f'{min(hi)}--{max(hi)}' if len(hi) > 1 else (str(hi[0]) if hi else '--')
    rows = []
    for c1, c2 in det['bpm_ranges']:
        n = c2 - c1 + 1
        amp = 1 if c2 < 1024 else 2
        rows.append(f'{c1}--{c2} & {n} & {amp} \\\\' if n > 1 else f'{c1} & 1 & {amp} \\\\')
    half = (len(rows) + 1) // 2
    body = []
    for i in range(half):
        r2_ = rows[i + half].rstrip('\\ ') if i + half < len(rows) else '& &'
        body.append(rows[i].rstrip('\\ ') + ' & ' + r2_ + ' \\\\')
    write_table('bpm', r'''\begin{table}[t]
  \centering\small
  \caption{Columns masked by default, in pixels of the trimmed, unbinned frame
    (spatial axis; amplifier~1 is 0--1023).}
  \label{tab:bpm}
  \begin{tabular}{lrclrc}
    \toprule
    Columns & $N$ & Amp. & Columns & $N$ & Amp. \\
    \midrule
''' + '\n'.join('    ' + r for r in body) + r'''
    \bottomrule
  \end{tabular}
\end{table}
''')

    # Dark current
    dk = det['dark']
    rates = [dk[n][a]['rate_e_hr'] for n in dk for a in '12']
    N['darkRate'] = f'{np.min(rates):.1f}--{np.max(rates):.1f}' if np.ptp(rates) > 0.2 \
        else f'{np.mean(rates):.1f}'
    ex = sorted({t for n in dk for t in dk[n]['1']['exptimes']})
    N['darkExptimes'] = '--'.join(f'{t:.0f}' for t in (ex[0], ex[-1])) if len(ex) > 1 else f'{ex[0]:.0f}'

    # Saturation and frames
    N['satLevel'] = f'{65535 * min(EGAIN):.0f}'


# ------------------------------------------------------------- calibrations ---
def calib_tables(N):
    cal = load('calibs.json')

    def one(ds):
        return list(cal[ds]['calibs'].values())[0]

    # Longslit segments
    sl = one('vph_red_longslit')['slits']['slits']
    widths = np.array([s['width_arcsec'] for s in sl])
    gaps = np.array([sl[i + 1]['left'] - sl[i]['right'] for i in range(len(sl) - 1)])
    N['nSegLongslit'] = str(len(sl))
    N['segLengthArcsec'] = f'{np.median(widths):.0f}'
    N['bridgePix'] = f'{np.median(gaps):.0f}'
    N['nSlitsBlueMos'] = str(one('vph_blue_mos')['slits']['nslits'])
    N['nSlitsRedMos'] = str(one('vph_red_mos')['slits']['nslits'])

    # Flats
    raws, norms, rms = [], [], []
    for ds in DATASETS:
        for c in cal[ds]['calibs'].values():
            f = c.get('flat', {})
            if f.get('seam_step_raw_pct') is not None:
                raws.append(abs(f['seam_step_raw_pct']))
            if f.get('seam_step_norm_pct') is not None:
                norms.append(abs(f['seam_step_norm_pct']))
    N['seamRawRange'] = f'{min(raws):.1f}--{max(raws):.1f}'
    N['seamNormRange'] = f'{min(norms):.2f}--{max(norms):.2f}'
    N['pixelflatRMS'] = f"{100 * one('vph_red_longslit')['flat']['pixelflat_rms']:.1f}"

    # Wavelength calibration table and grism table
    rows, grows = [], []
    for ds, (grism, mode, label) in DATASETS.items():
        boxes = set(cal[ds]['boxes'])
        for key, c in cal[ds]['calibs'].items():
            nsci = sum(1 for s in c['wave']['slits'] if s['spat_id'] not in boxes)
            w = [s for s in c['wave']['slits'] if s.get('ok') and s['spat_id'] not in boxes]
            if not w:
                continue
            disp = np.array([s['disp'] for s in w])
            med = np.median(disp)
            good = np.abs(disp / med - 1) < 0.05
            wg = [s for s, g in zip(w, good) if g]
            nl = np.array([s['nlin'] for s in wg])
            ra = np.array([s['rms_ang'] for s in wg])
            rp = np.array([s['rms_pix'] for s in wg])
            R = np.array([s['R'] for s in wg])
            fw = np.array([s['fwhm_ang'] for s in wg])
            cw = np.array([s['cen_wave'] for s in wg])
            kms = 2.998e5 * ra / cw
            lab = label.replace('_', r'\_').replace('"', "''")
            rows.append(f'{lab} & {key.split("_")[-2]} & {len(wg)}/{nsci} & '
                        f'{np.median(nl):.0f} & {np.median(ra):.3f} & {np.median(rp):.2f} & '
                        f'{np.median(kms):.0f} & {np.median(fw):.1f} & {np.median(R):.0f} \\\\')
            if mode == 'longslit':
                # central segment: the one closest to the detector centre
                seg = min(wg, key=lambda s: abs(s['spat_id'] - 1024))
                grows.append((grism, seg))
    write_table('wavecal', r'''\begin{table}[t]
  \centering\small
  \caption{Wavelength-calibration performance. For each data set and calibration
    group: slits with a valid solution out of the science slits traced (alignment
    holes excluded); and, as medians over
    those slits, the number of lines in the fit, the RMS residual in \AA, pixels
    and \si{\kilo\metre\per\second}, the FWHM of the arc lines and the resolving
    power $R=\lambda_{\rm c}/{\rm FWHM}$ at the central wavelength for the
    \SI{1}{arcsec} slit.}
  \label{tab:wavecal}
  \begin{tabular}{lcccccccc}
    \toprule
    Data set & Group & Slits & $N_{\rm lines}$ & RMS (\AA) & RMS (pix) & RMS (km/s) & FWHM (\AA) & $R$ \\
    \midrule
''' + '\n'.join('    ' + r for r in rows) + r'''
    \bottomrule
  \end{tabular}
\end{table}
''')
    grows_ = []
    for grism in ('VPH-Blue', 'VPH-Red', 'VPH-All'):
        s = [g for gg, g in grows if gg == grism][0]
        filt = {'VPH-Blue': 'none', 'VPH-Red': 'OG590', 'VPH-All': 'none'}[grism]
        grows_.append(f"{grism} & {s['wmin']:.0f}--{s['wmax']:.0f} & "
                      f"{s['wline_min']:.0f}--{s['wline_max']:.0f} & {s['disp']:.3f} & "
                      f"{s['cen_wave']:.0f} & {s['fwhm_ang']:.1f} & {s['R']:.0f} & {filt} \\\\")
        N[f"rms{grism.split('-')[1].capitalize()}"] = f"{s['rms_ang']:.3f}"
    write_table('grisms', r'''\begin{table}[htb]
  \centering\small
  \caption{The LDSS3-C grisms as calibrated here, for the central segment of the
    \SI{1.0}{arcsec} longslit: wavelength range of the solution and range covered
    by identified arc lines, dispersion and central wavelength, arc-line FWHM and
    resolving power, and the order-blocking filter used in the data of this
    report.}
  \label{tab:grisms}
  \begin{tabular}{lccccccl}
    \toprule
    Grism & Range (\AA) & Lines (\AA) & \AA/pix & $\lambda_{\rm c}$ (\AA) & FWHM (\AA) & $R$ & Filter \\
    \midrule
''' + '\n'.join('    ' + r for r in grows_) + r'''
    \bottomrule
  \end{tabular}
\end{table}
''')

    # Science: flexure, seam wavelength jump, noise, sky-line zero point
    flex, jumps, sp, se = [], [], [], []
    sky = {}
    for ds in DATASETS:
        boxes = set(cal[ds]['boxes'])
        for s in cal[ds]['science']:
            if s.get('seam_wave_jump'):
                jumps.append(abs(s['seam_wave_jump']['median']))
            if 'science' in s['frametype']:
                sp.append(s['noise']['sigma_published'])
                se.append(s['noise']['sigma_enoise'])
                for o in s.get('objects', []):
                    if o['flex_shift'] is not None and o['slit'] not in boxes:
                        flex.append(o['flex_shift'])
            if ds in NO_OBJECT:
                continue
            for sid, x in (s.get('sky_lines') or {}).items():
                if int(sid) not in boxes:
                    sky.setdefault(ds, []).append((x['median'], x['n'], x['disp']))
    br = {}
    for ds in DATASETS:
        if ds in NO_OBJECT:
            continue
        for s_ in cal[ds]['science']:
            if 'science' in s_['frametype']:
                br.setdefault(ds, []).append((s_['noise']['sigma_faintsky'], s_['noise']['sigma_brightsky']))
    for ds, key in (('vph_red_longslit', 'RedLS'), ('vph_blue_mos', 'BlueMOS')):
        v = np.array(br[ds])
        N[f'chiFaint{key}'] = f'{np.median(v[:, 0]):.2f}'
        N[f'chiBright{key}'] = f'{np.median(v[:, 1]):.2f}'
    flex = np.array(flex)
    N['flexRange'] = f'{flex.min():+.1f} to {flex.max():+.1f}'
    N['flexMaxAbs'] = f'{np.max(np.abs(flex)):.1f}'
    N['seamWaveJump'] = f'{max(jumps):.3f}' if jumps else 'not measurable'
    rowmax = [s_['seam_wave_jump']['max_abs'] for ds in DATASETS for s_ in cal[ds]['science']
              if s_.get('seam_wave_jump')]
    N['seamWaveJumpRowMax'] = f'{max(rowmax):.2f}'
    N['sigmaChiPublished'] = f'{np.median(sp):.2f}'
    N['sigmaChiEnoise'] = f'{np.median(se):.2f}'
    N['sigmaChiRange'] = f'{min(sp):.2f}--{max(sp):.2f}'
    rows = []
    for ds, v in sky.items():
        v = np.array(v)
        grism, mode, label = DATASETS[ds]
        lab = label.replace('_', r'\_').replace('"', "''")
        rows.append(f"{lab} & {len(v)} & {int(np.median(v[:, 1]))} & "
                    f"{np.median(v[:, 0]):+.2f} & {np.max(np.abs(v[:, 0])):.2f} & "
                    f"{np.max(np.abs(v[:, 0])) / np.median(v[:, 2]):.2f} \\\\")
    allmed = np.concatenate([np.array(v)[:, 0] for v in sky.values()])
    # Red end of VPH-Red, beyond the reddest arc line
    red = [o for s_ in cal['vph_red_longslit']['science']
           for sid, x in (s_.get('sky_lines') or {}).items()
           for l, o in zip(x['lines'], x['offsets']) if l > 9800]
    N['skyRedEndN'] = str(len(red))
    N['skyRedEndMedian'] = f'{np.median(red):+.2f}'
    N['skyRedEndStd'] = f'{np.std(red):.2f}'
    N['skyOffsetMax'] = f'{np.max(np.abs(allmed)):.2f}'
    write_table('skylines', r'''\begin{table}[t]
  \centering\small
  \caption{Wavelength zero point of the science frames, from Gaussian fits to
    isolated sky emission lines ([OI] and OH) in the final, flexure-corrected
    wavelength frame. For each data set: number of slit-exposure pairs, median
    number of lines per slit, and the median and largest per-slit offset
    (measured $-$ reference).}
  \label{tab:skylines}
  \begin{tabular}{lrrrrr}
    \toprule
    Data set & Slits$\times$exp. & $N_{\rm lines}$ & Median (\AA) & Max.\ $|\Delta|$ (\AA) & Max.\ $|\Delta|$ (pix) \\
    \midrule
''' + '\n'.join('    ' + r for r in rows) + r'''
    \bottomrule
  \end{tabular}
\end{table}
''')

    # Alignment holes
    nb = {ds: len(cal[ds]['boxes']) for ds in ('vph_blue_mos', 'vph_red_mos')}
    N['nBoxesBlue'] = str(nb['vph_blue_mos'])
    N['nBoxesRed'] = str(nb['vph_red_mos'])
    N['nSciSlitsBlue'] = str(one('vph_blue_mos')['slits']['nslits'] - nb['vph_blue_mos'])
    N['nSciSlitsRed'] = str(one('vph_red_mos')['slits']['nslits'] - nb['vph_red_mos'])


def dataset_table(N):
    """Frames used per data set, from the PypeIt files."""
    from pypeit.inputfiles import PypeItFile
    rows, nframes = [], 0
    for ds, (grism, mode, label) in DATASETS.items():
        p = PypeItFile.from_file(REDUX / ds / f'{ds}.pypeit')
        t = p.data
        nframes += len(t)
        ft = [str(f) for f in t['frametype']]
        n = lambda s: sum(s in f.split(',') for f in ft)                 # noqa: E731
        mjd = np.array(t['mjd'], dtype=float)
        from astropy.time import Time
        dates = sorted({Time(m, format='mjd').strftime('%Y-%m-%d') for m in mjd})
        date = dates[0] if len(dates) == 1 else f'{dates[0]} -- {dates[-1][5:]}'
        targets = sorted({str(x).split(' - ')[0].split(' VPH')[0].split('_science')[0]
                          .replace('science ', '')
                          for x, f in zip(t['target'], ft) if 'science' in f or 'standard' in f})
        filt = sorted(set(str(x) for x in t['filter1']))
        rows.append(f"{grism} & {t['decker'][0].replace('_', r'\_')} & {', '.join(filt)} & {date} & "
                    f"{n('arc')} & {n('pixelflat')} & {n('science') + n('standard')} & "
                    f"{', '.join(targets).replace('_', r'\_') or '--'} \\\\")
    N['nFramesTyped'] = str(sum(1 for _ in open(REDUX.parent / 'setup_files' / 'magellan_ldss3.obslog')
                                if _.strip().startswith('ccd')) or nframes)
    write_table('datasets', r'''\begin{table}[t]
  \centering\small
  \caption{Data sets reduced for this report: number of arc, flat and
    science/standard exposures used.}
  \label{tab:datasets}
  \begin{tabular}{llllrrrl}
    \toprule
    Grism & Slit/mask & Filter & Date (UT) & Arcs & Flats & Sci. & Targets \\
    \midrule
''' + '\n'.join('    ' + r for r in rows) + r'''
    \bottomrule
  \end{tabular}
\end{table}
''')


def param_table(N):
    """Parameters changed by the LDSS3 class with respect to the PypeIt defaults."""
    from pypeit.par.pypeitpar import PypeItPar
    from pypeit.spectrographs.util import load_spectrograph
    import pypeit
    N['pypeitVersion'] = pypeit.__version__.replace('_', r'\_')
    base = PypeItPar().to_config()
    ldss = load_spectrograph('magellan_ldss3').default_pypeit_par().to_config()
    base = {l.strip() for l in base}

    rows = []
    path = []
    for line in ldss:
        s = line.strip()
        if not s or s.startswith('#'):
            continue
        if s.startswith('['):
            depth = s.count('[') // 2 if s.startswith('[[') else 1
            depth = len(s) - len(s.lstrip('['))
            name = s.strip('[]')
            path = path[:depth - 1] + [name]
            continue
        if s not in base:
            k, v = [x.strip() for x in s.split('=', 1)]
            v = v.rstrip(',')
            rows.append((' / '.join(path), k, v))
    # Keep the ones that matter to users, dropping per-frame duplicates
    seen, body = set(), []
    for p, k, v in rows:
        short = p.replace('calibrations / ', '')
        if 'process' in p and k in ('use_biasimage', 'use_darkimage'):
            key = ('process', k)
            if key in seen:
                continue
            seen.add(key)
            short = '(all frames) process'
        body.append(f"\\code{{{short.replace('_', r'\_')}}} & \\code{{{k.replace('_', r'\_')}}} & "
                    f"\\code{{{v.replace('_', r'\_')}}} \\\\")
    write_table('params', r'''\begin{longtable}{lll}
  \caption{Parameters set by the LDSS3-C spectrograph class that differ from the
    \pypeit{} defaults (\code{default\_pypeit\_par}). Grism-dependent settings
    (\code{config\_specific\_par}) are the wavelength template
    (\code{reid\_arxiv}), \code{method = full\_template}, \code{lamps = HeI, NeI,
    ArI}, and \code{fwhm} = 6 binned pixels; for longslit masks
    \code{sync\_predict = nearest}.}
  \label{tab:params}\\
  \toprule
  Parameter group & Parameter & Value \\
  \midrule
  \endfirsthead
  \toprule
  Parameter group & Parameter & Value \\
  \midrule
  \endhead
''' + '\n'.join('  ' + r for r in body) + r'''
  \bottomrule
\end{longtable}
''')


def main():
    TABLES.mkdir(exist_ok=True)
    N = Numbers()
    N['reportdate'] = datetime.date.today().strftime('%B %Y')
    oh = [l for l in open(Path(__import__('pypeit').__file__).parent / 'data' / 'arc_lines'
                          / 'lists' / 'OH_LDSS3_vac_lines.dat')
          if l.startswith('|') and l.split('|')[1].strip().replace('.', '', 1).isdigit()]
    N['nOHlines'] = str(len(oh))
    detector_tables(N)
    calib_tables(N)
    dataset_table(N)
    param_table(N)
    N.write()


if __name__ == '__main__':
    main()
